# Generated by Django 5.0.1 on 2024-05-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='contents_count',
        ),
    ]
