# Generated by Django 5.0.1 on 2024-05-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_department_contents_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contents_count',
            field=models.IntegerField(default=0),
        ),
    ]
