# Generated by Django 5.0.1 on 2024-05-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_username_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
