# Generated by Django 5.0.1 on 2024-05-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.CharField(default='Default Department', max_length=100),
        ),
    ]
